### ISSUE TITLE
Week 1 Review Ticket

### ISSUE THREAD

**Issue by Rebecca-123** [TheRadRabbidRabbit/Team-Lovelace#11]
**Scrum Team Project Review**
- [x] Design - Wiki Theme, Brain Write & Wire Frame
- [Link to issue](https://github.com/TheRadRabbidRabbit/Team-Lovelace/issues/10)
- [x] Technicals - 10  to 12 key ideas 
- [x] Github - On Wiki containing Management Plan
- [Link to plan](https://github.com/TheRadRabbidRabbit/Team-Lovelace/wiki/Company-Policies#management-plan)
- Discussion of policies on other page in wiki
- [x] Deployment - Wiki Plan, Hardware and Frequency
- [x] Scrum Board - Assignments and Backlog

**[Individual TPT Issue](https://github.com/TheRadRabbidRabbit/Team-Lovelace/issues/9)**
- Individual Create Task Understanding and Score, Notes, on TPT
- TPT 0.0, Create Task ideas, notes, and research
- 1.3 Program Design and Development
- 1.4 Identifying and Correcting Errors

**Grading Plan**
- [x] Readme Time-box and Review Ticket required
- [x] Live grading from preliminary grading Review Ticket by Teacher on Th and F, including adjustments from cross over grading
- [x] Final, old point review.  Adjustment from Seed or Week 0

**Comment by xiaoa0** [comment]
| Name | Individual score | Group score | Total score |
| :----| :----------------| :-----------| :----------:|
| Allie |    |    |    |
| Justin |   |    |    |
| Rebecca |   |   |   |
| Tianbin |   |   |   |
| Gabriel |   |   |   |

**Comment by Rebecca-123** [comment]
Crossover Grading
Overall score - 5/5  
Explanation - Evidence of great effort and work on the website. Each of the technical ideas was well thought out and feasible. In addition, scrum board was well organized with tags to aid in organization.  The wiki was organized well on part of the design manager, and the wiki deployment plan and commit plan were easy to follow.  Contributor requirements were also the same.

**Comment by jm1021** [comment]
Lovelace - Allie 4.9/5
* Impressive subpage with all design request 1/1
* Very nice ideas on CB site 1/1
* Management Plan, incorporates Git 1/1
* Deployment, backup plan, frequency .9/1
* Good structure 1/1

**Comment by jm1021** [comment]
Nice job on capturing details of week for grading!  +0.1. 5/5 is my new score

**Comment by jm1021** [comment]
Max score is 8/8 based on individual success in TPT.
